In [1]:
import keras

Using TensorFlow backend.


In [6]:
'''今天
天氣
很好
'''


'今天\n天氣\n很好\n'

In [12]:
## dictionary
List = [[0,1],[2,3],[5,6,7]]                
List[2][0]


5

In [19]:
grades = [85,70,80]
weights = [0.2,0.35,0.45]

sum = 0
for i in range(3):
    sum += grades[i] * weights[i]
    
print(sum)

77.5


In [52]:
import numpy as np

print(np.average(grades))
print(np.max(grades))
print(np.std(grades))

s = np.array([-3,2,7,-5.2])
s[s > 0]

a = np.arange(28)
#a.shape = (7,4)
print(a)

b = np.reshape(a,[7,4])
print(a)
print(b)

gs = np.array([85,70,80])
ws = np.array([0.2,0.35,0.45])
print(np.sum(gs * ws))

78.3333333333
85
6.23609564462
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
77.5


In [56]:
import numpy as np
from datetime import datetime

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a,b):
    result = 0
    for e, f in zip(a, b):
        result += e*f
    return result

t0 = datetime.now()
for t in range(T):
    slow_dot_product(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
    a.dot(b)
dt2 = datetime.now() - t0
print(dt1.total_seconds()/dt2.total_seconds())

np.linspace

31.664331321752147


In [7]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import gi

x = np.linspace(-5, 5, 500)
y = np.sin(2*x) + np.exp(x/2)
plt.plot(x,y)





ModuleNotFoundError: No module named 'gi'

In [8]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import gi

plt.switch_backend('agg')

gi.res(gi.base64(plt))

ModuleNotFoundError: No module named 'gi'

In [11]:
import pandas as pd

mydata = np.random.randn(4,3)


